#!/usr/bin/env python3
"""
Figma Integration Setup Script for Earth Saver Game
Creates folders, template files, and integration helpers
"""

import os
from pathlib import Path

def create_figma_structure():
    """Create folder structure for Figma assets"""
    folders = [
        "assets/images/figma",
        "assets/images/figma/backgrounds",
        "assets/images/figma/buttons", 
        "assets/images/figma/icons",
        "assets/images/figma/sprites",
        "assets/images/figma/ui-elements",
        "assets/css/figma"
    ]
    
    print("Creating Figma integration structure...")
    
    for folder in folders:
        Path(folder).mkdir(parents=True, exist_ok=True)
        print(f"   Created: {folder}")
    
    return folders

def create_figma_css_template():
    """Create CSS template for Figma design integration"""
    
    css_content = """/* Figma Design Integration - Homepage Styles
   Generated by Earth Saver Figma Setup Script
*/

/* Import our base pixel art framework */
@import url('../pixel-styles.css');

/* FIGMA DESIGN VARIABLES */
:root {
    /* Replace with your Figma colors */
    --figma-primary: #0066FF;
    --figma-secondary: #00AA00;
    --figma-accent: #FFAA00;
    --figma-text: #222222;
    --figma-background: #FFFFFF;
    
    /* Adapt to pixel variables */
    --figma-border: 4px solid var(--pixel-black);
    --figma-shadow: 6px 6px 0 var(--pixel-black);
}

/* FIGMA LAYOUT COMPONENTS */
.figma-homepage-container {
    max-width: 1200px;
    margin: 0 auto;
    padding: 20px;
    font-family: var(--pixel-font-family);
    image-rendering: pixelated;
}

.figma-hero-section {
    background: var(--figma-background);
    border: var(--figma-border);
    box-shadow: var(--figma-shadow);
    padding: 40px;
    margin-bottom: 30px;
}

.figma-card {
    background: var(--figma-background);
    border: var(--figma-border);
    box-shadow: var(--figma-shadow);
    padding: 20px;
    margin: 15px 0;
    border-radius: 0;
    transition: none;
}

.figma-card:hover {
    transform: translate(2px, 2px);
    box-shadow: 4px 4px 0 var(--pixel-black);
}

.figma-button {
    background: var(--figma-primary);
    color: white;
    border: var(--figma-border);
    box-shadow: var(--figma-shadow);
    padding: 12px 24px;
    font-family: var(--pixel-font-family);
    font-weight: bold;
    text-transform: uppercase;
    cursor: pointer;
    border-radius: 0;
    transition: none;
}

.figma-button:hover {
    background: var(--figma-accent);
    transform: translate(2px, 2px);
    box-shadow: 4px 4px 0 var(--pixel-black);
}

/* FIGMA ICONS & SPRITES */
.figma-icon {
    width: 32px;
    height: 32px;
    image-rendering: pixelated;
    image-rendering: -moz-crisp-edges;
    image-rendering: crisp-edges;
}

/* RESPONSIVE DESIGN */
@media (max-width: 768px) {
    .figma-homepage-container {
        padding: 15px;
    }
    
    .figma-hero-section {
        padding: 20px;
    }
    
    .figma-card {
        margin: 10px 0;
        padding: 15px;
    }
}

/* INTEGRATION HELPERS */
.figma-pixel-blend {
    image-rendering: pixelated;
    border-radius: 0 !important;
    box-shadow: var(--pixel-shadow);
}

/* ANIMATIONS */
@keyframes figma-pixel-bounce {
    0%, 100% { transform: translateY(0); }
    50% { transform: translateY(-8px); }
}

.figma-animated {
    animation: figma-pixel-bounce 2s steps(4, end) infinite;
}
"""
    
    css_file = "assets/css/figma/homepage-design.css"
    with open(css_file, 'w', encoding='utf-8') as f:
        f.write(css_content)
    
    print(f"   Created CSS template: {css_file}")
    return css_file

def create_figma_integration_guide():
    """Create integration guide"""
    
    guide_content = """# Figma to Earth Saver Integration Guide

## Quick Start Checklist

### 1. Export Assets from Figma
- [ ] Images: Export as PNG (2x) to `assets/images/figma/`
- [ ] Icons: Export as SVG to `assets/images/figma/icons/`
- [ ] Backgrounds: Export as PNG to `assets/images/figma/backgrounds/`
- [ ] UI Elements: Export as PNG to `assets/images/figma/ui-elements/`

### 2. Export CSS from Figma
- [ ] Use Figma Dev Mode (Inspect Panel)
- [ ] Or use plugins: Anima, Figma to CSS, etc.
- [ ] Copy CSS rules to `assets/css/figma/homepage-design.css`

### 3. Integration Steps
- [ ] Paste Figma CSS into the template file
- [ ] Replace colors with our pixel art variables
- [ ] Add pixel art borders and shadows
- [ ] Remove border-radius (keep sharp edges)
- [ ] Update image paths to figma folder

## File Structure Created

```
assets/
├── css/figma/
│   └── homepage-design.css     # Your Figma CSS goes here
└── images/figma/
    ├── backgrounds/            # Background images
    ├── buttons/               # Button sprites
    ├── icons/                 # Icon assets
    ├── sprites/              # Game sprites
    └── ui-elements/          # UI components
```

## Integration Methods

### Method 1: Replace Homepage (Full Figma Design)
```html
<!-- In src/homepage.html -->
<link rel="stylesheet" href="../assets/css/pixel-styles.css">
<link rel="stylesheet" href="../assets/css/figma/homepage-design.css">
```

### Method 2: Hybrid Approach (Recommended)
Keep pixel art framework + add Figma enhancements

### Method 3: A/B Testing
Create alternative homepage version:
```bash
cp src/homepage.html src/homepage-figma.html
```

## Color Conversion Guide

Replace Figma colors with our pixel variables:

| Figma Color | Pixel Variable |
|-------------|----------------|
| `#0066FF` | `var(--pixel-earth-blue)` |
| `#00AA00` | `var(--pixel-earth-green)` |
| `#FF2222` | `var(--pixel-critical-red)` |
| `#FFAA00` | `var(--pixel-warning-yellow)` |
| `#FFFFFF` | `var(--pixel-white)` |
| `#000000` | `var(--pixel-black)` |

## Layout Adaptation Rules

1. **Maintain Structure**: Keep Figma layout hierarchy
2. **Add Pixel Borders**: `border: 4px solid var(--pixel-black)`
3. **Chunky Shadows**: `box-shadow: 6px 6px 0 var(--pixel-black)`
4. **No Rounded Corners**: `border-radius: 0`
5. **Pixelate Images**: `image-rendering: pixelated`

## Testing Your Integration

1. **Start Server**: `python config/server.py`
2. **Navigate**: Go to homepage after login
3. **Debug**: Check browser console for asset loading
4. **Responsive**: Test on mobile/tablet views

## Pro Tips

- Export Figma assets at 2x resolution for crisp display
- Use PNG for complex graphics, SVG for simple icons
- Maintain our pixel art aesthetic while adding your design flair
- Test on different screen sizes to ensure responsive design

## Troubleshooting

**Images not loading?**
- Check file paths in CSS
- Ensure assets are in correct folders
- Verify image file extensions match CSS

**CSS not applying?**
- Check CSS file is linked in HTML
- Verify CSS syntax is valid
- Use browser dev tools to debug

**Layout broken on mobile?**
- Add responsive rules to Figma CSS
- Test with browser dev tools device emulation

---

**Ready to integrate your Figma design? Follow the checklist above!**
"""
    
    guide_file = "assets/figma-integration-guide.md"
    with open(guide_file, 'w', encoding='utf-8') as f:
        f.write(guide_content)
    
    print(f"   Created integration guide: {guide_file}")
    return guide_file

def create_asset_placeholders():
    """Create placeholder files to show expected structure"""
    
    placeholders = {
        "assets/images/figma/README.md": """# Figma Assets Folder

## Folder Structure

- `backgrounds/` - Background images from Figma
- `buttons/` - Button sprites and states  
- `icons/` - Icon assets (32x32 recommended)
- `sprites/` - Game-related sprites
- `ui-elements/` - UI components and decorations

## Export Guidelines

- **Resolution**: 2x for retina displays
- **Format**: PNG for complex images, SVG for simple icons
- **Naming**: Use kebab-case (e.g., `hero-background.png`)
- **Size**: Optimize for web (use tools like TinyPNG)

## Integration

After exporting assets here, update the CSS file:
`assets/css/figma/homepage-design.css`
""",
        
        "assets/images/figma/backgrounds/.gitkeep": "# Export Figma backgrounds here",
        "assets/images/figma/buttons/.gitkeep": "# Export Figma buttons here", 
        "assets/images/figma/icons/.gitkeep": "# Export Figma icons here",
        "assets/images/figma/sprites/.gitkeep": "# Export Figma sprites here",
        "assets/images/figma/ui-elements/.gitkeep": "# Export Figma UI elements here"
    }
    
    for file_path, content in placeholders.items():
        with open(file_path, 'w', encoding='utf-8') as f:
            f.write(content)
        print(f"   Created placeholder: {file_path}")

def main():
    """Main setup function"""
    print("Earth Saver - Figma Integration Setup")
    print("=" * 50)
    
    # Verify we're in the right place
    if not Path('index.html').exists():
        print("Error: Please run this script from the project root directory")
        return
    
    try:
        # Create folder structure
        folders = create_figma_structure()
        
        # Create template files
        css_template = create_figma_css_template()
        guide_file = create_figma_integration_guide()
        
        # Create helper files
        create_asset_placeholders()
        
        print("\n" + "=" * 50)
        print("Figma Integration Setup Complete!")
        print("=" * 50)
        
        print("\nNext Steps:")
        print("1. Export your Figma design assets to: assets/images/figma/")
        print("2. Copy Figma CSS to: assets/css/figma/homepage-design.css") 
        print("3. Read the guide: assets/figma-integration-guide.md")
        print("4. Test integration: python config/server.py")
        
        print("\nReady for your Figma design!")
        
    except Exception as e:
        print(f"\nSetup failed: {e}")
        print("Please check permissions and try again.")

if __name__ == "__main__":
    main()